name: MLOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - name: Activate virtual environment
      run: |
        python -m venv virtual
        ./virtual/Scripts/activate
        pip list
        

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iris:$(date +%s)
